import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { BookOpen } from 'lucide-react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="block sticky top-0 z-30 bg-white dark:bg-slate-800 border-b dark:border-slate-700 p-4">
          <div className="flex items-center">
            <div className="w-8 h-8 bg-gradient-to-br to-leather-600 rounded-full flex items-center justify-center">
              <BookOpen className="text-white" size={16} />
            </div>
            <span className="text-lg font-bold">Brandobook</span>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
